/*
-- Query: SELECT * FROM catelog.major
-- Date: 2020-11-11 19:40
*/
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Accounting','ACCT');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Center For Arabic Studies Abroad','AIAS');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Arabic Language Intensive','ALIN');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Arabic Language Intensive Summer','ALIS');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Arabic Language','ALNG');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Arabic Writing','ALWT');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('American Studies','AMST');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Anthropology','ANTH');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Applied Linguistics','APLN');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Architectural Engineering','ARCH');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Arab and Islamic Civilizations','ARIC');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Visual Arts','ARTV');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Business Administration','BADM');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Biology','BIOL');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Biotechnology','BIOT');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Business School','BUSC');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('International Management','CEMS');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Construction Engineering','CENG');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Chemistry','CHEM');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Core Curriculum','CORE');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Comparative Religion','CREL');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Computer Science and Engineering','CSCE');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Data Science','DSCI');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Graphic Design','DSGN');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('English & Comparative Literature','ECLT');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Electronics and Communications Engineering','ECNG');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Economics','ECON');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Education','EDUC');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Egyptology','EGPT');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Intensive English','ELIN');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Executive Business Administration','EMBA');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('English','ENGL');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Engineering','ENGR');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Entrepreneurship','ENTR');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Environmental Engineering','ENVE');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Film','FILM');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Finance','FINC');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Global Public Health','GHHE');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Sustainable Development','GREN');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Gender and Women’s Studies','GWST');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('History','HIST');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('International Business','INTB');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Journalism & Mass Communication','JRMC');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Libraries and Learning Technologies','LALT');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('International Human Rights Law','LAW');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Linguistics','LING');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Mathematics and Actuarial Science','MACT');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Mechanical Engineering','MENG');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Middle East Studies','MEST');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Management','MGMT');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Marketing','MKTG');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Management of Information Systems','MOIS');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Migration & Refugee Studies','MRS');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Music','MUSC');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Nanotechnology','NANO');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Operations Management','OPMG');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Petroleum Engineering','PENG');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Ph.D. in Engineering','PHDE');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Ph.D. in Applied Sciences','PHDS');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Philosophy','PHIL');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Physics','PHYS');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Political Science','POLS');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Public Policy and Administration','PPAD');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Psychology','PSYC');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Robotics, Control and Smart Systems','RCSS');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Rhetoric and Composition','RHET');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Science','SCI');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Seminar','SEMR');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Sociology','SOC');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Teaching & Learning','TEAL');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Theatre','THTR');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Translation Studies','TRST');
INSERT INTO `` (`major_name`,`major_code`) VALUES ('Television and Digital Journalism','TVDJ');
